orders/urls.py
from django.conf.urls import url
from django.urls.conf import path 
from orders import views

urlpatterns = [
    path('reqorderlist/', views.requestOrder_list), 
    path('requestorder/<int:pk>', views.reqOrder_detail),
    path('deliveryloglist/',views.DeliveryLog_list),
    path('deliverylog/<int:pk>',views.DeliveryLog_detail),
    path('stockList/',views.Stock_list),
    path('stock',views.Stock_detail),
    path('orderList/',views.Order_list),
    path('order/<int:pk>',views.Order_detail),
    path('items/',views.Item_list),
    path('reorder/<int:pk>',views.Reorder_level)
    
    
]

procurement/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.urls import path
from orders import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='login_page'), #login page
    path('login/', views.login_web, name='login_check'),
    path('logout/', views.logout_view, name='logout_view'),

    path('requests/', views.ViewRequests.as_view(), name='list_order_requests'), 
    path('requests/<int:pk>/', views.view_order_request, name='view_order_request'), #puchase order view
    path('requests/<int:pk>/purchase-orders', views.create_purchase_order, name='purchase_order_add'), #puchase order view

    path('items/', views.ViewItems.as_view(), name='items_catalog'), 
    path('items/add', views.add_items, name='items_add'), 
    path('items/<int:pk>/prices', views.CreateItemPrices.as_view(), name='item_prices_view'), 
    path('items/<int:pk>/prices/add', views.add_prices, name='item_prices_add'), 
    path('items/<int:pk>/prices/delete', views.delete_prices, name='item_prices_remove'), 
    path('purchase-orders/', views.ViewPurchaseOrders.as_view(), name='list_purchase_order'), 
    path('requests/<int:request_id>/purchase-orders/<int:order_id>', views.update_purchase_order, name='update_purchase_order'), 
   
    path('rulelist/', views.Ruleslist.as_view(), name='rulelist'),

    path('rules/rule1', views.AddItemRule.as_view(), name='rule1add'),
    path('rule1status/rule1status', views.getItemRule, name='rule1status'),

    path('rules/rule2', views.AddPriceRule.as_view(), name='rule2add'),
    path('rule1status/rule2status', views.getPriceRule, name='rule2status'),

    path('rules/rule3', views.AddlevelRule.as_view(), name='rule3add'),
    path('rule1status/rule3status', views.getlevelRule, name='rule3status'),

    path('getdata/', views.manage_approvals, name='getdata'),
    path('manage/', views.Approvals.as_view(), name='manage'),

    path('itemrule/', views.status_rule_one, name='itemrule'),
    path('pricerule/', views.status_rule_two, name='pricerule'),
    path('editrequest/', views.status_edit_requests, name='editrequest'),
    path('deleterequest/', views.status_delete_requests, name='deleterequest'),
    path('managerapprove/', views.status_rule_three, name='managerapprove'),








    url('apis/', include('orders.urls')),




]

orders/models.py
from django.db import models
from django.contrib.auth.models import User as user
# Create your models here.


class Location(models.Model):
    address_line1 = models.CharField(max_length=50)
    address_line2 = models.CharField(max_length=50)
    address_line3 = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=50)
    postal_code = models.CharField(max_length=50)

    def __str__(self):
        add = self.address_line1 + ', ' + self.address_line2 + ', '
        if self.address_line3 is not None:
            add = add + self.address_line3 + ', '
        add = add + self.city + ' (' + self.postal_code + ') '
        return add

    def get_address(self):
        """"Return the address as a string"""
        add = self.address_line1 + ', ' + self.address_line2 + ', '
        if self.address_line3 is not None:
            add = add + self.address_line3 + ', '
        add = add + self.city + ' (' + self.postal_code + ') '
        return add


class Site(models.Model):
    name = models.CharField(max_length=50)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    contact_number = models.CharField(max_length=15)
    budget = models.FloatField

    def __str__(self):
        return self.name


class Supplier(models.Model):
    company_name = models.CharField(max_length=50)
    company_address = models.ForeignKey(Location, on_delete=models.CASCADE)
    contact_number = models.CharField(max_length=13)
    email = models.CharField(max_length=50)


class UserType(models.Model):
    name =  models.CharField(max_length=50)  
    abbv =  models.CharField(max_length=13) #MANG #SUPV #SMANG #ACCST

    def __str__(self):
        return self.name


class Employee(models.Model):
    user = models.OneToOneField(#One to one ? 
        user, on_delete=models.CASCADE, null=True, blank=True)
    firstname = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    contact_number = models.CharField(max_length=13)
    employee_type = models.ForeignKey(UserType, on_delete=models.CASCADE)
    location = models.ForeignKey(
        Site, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.firstname + ' ' + self.lastname



class Item(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        return self.name


class ItemPrices(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    price = models.CharField(max_length=50)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['item', 'supplier', 'price'], name='item_suppliers')
        ]


class Stock(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE,null=True)
    quantity = models.IntegerField(default=0)
    site = models.ForeignKey(Site, on_delete=models.CASCADE, null=True)
    quantity_type = models.CharField(max_length=15)
    reorder_level = models.IntegerField(default=10, null=True, blank=True)


class OrderStatus(models.Model):
    status = models.CharField(max_length=50)  # the string is already defined
    # can use the abbreviation to set the status : PEND, APPV, PAPPV, DECL, RETRND, DELET, REFERD
    abbv = models.CharField(max_length=6)
    # get the object through OrderStatus.objects.get(abbv=PEND) gives Pending object


class RequestOrders(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField(null=True)
    expected_date = models.CharField(max_length=50, null=True)
    comment = models.CharField(max_length=50, null=True, blank=True)
    site = models.ForeignKey(Site, on_delete=models.CASCADE,null=True)
    status = models.ForeignKey(OrderStatus, on_delete=models.CASCADE,null=True)
    auto_genarated=models.BooleanField(default=False)
    quantity_type=models.CharField(max_length=50,null=True)
    
    def __str__(self):
        return self.item.name


class Orders(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1, null=True, blank=True)
    remaining_quantity = models.IntegerField(null=True)
    quantity_type = models.CharField(max_length=15, null=True, blank=True)
    price = models.FloatField(null=True, blank=True)
    supplier = models.ForeignKey(
        Supplier, on_delete=models.CASCADE, null=True, blank=True)
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    status = models.ForeignKey(OrderStatus, on_delete=models.CASCADE)
    approved_by = models.ForeignKey(
        UserType, on_delete=models.CASCADE, null=True, blank=True)
    delivery_date = models.CharField(max_length=50)
    active = models.BooleanField(default=True)
    request = models.OneToOneField(RequestOrders, on_delete=models.CASCADE)#make this a one to one feild
    # do we need a comment here as in RequestOrders


class Rule1(models.Model):
    rule_code = models.CharField(max_length=15)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    active_status = models.BooleanField(default=True)


class Rule2(models.Model):
    rule_code = models.CharField(max_length=15)
    price_limit = models.FloatField(null=True, blank=True)
    active_status = models.BooleanField(default=True)


class Rule3(models.Model):
    rule_code = models.CharField(max_length=15)
    level = models.IntegerField(default=1, null=True, blank=True)
    active_status = models.BooleanField(default=True)


class DeliveryLog(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, null=True)
    purchased_orders = models.ForeignKey(
        Orders, on_delete=models.CASCADE, null=True)
    date = models.CharField(max_length=50)
    quantity = models.IntegerField(blank=True, null=True)


class Pending_orders(models.Model):
    orderno = models.ForeignKey(Orders, on_delete=models.CASCADE)
    Ruletype1 = models.IntegerField(default=0,null=False, blank=False)
    Ruletype2 = models.IntegerField(default=0,null=False, blank=False)
    Ruletype3 = models.IntegerField(default=0,null=False, blank=False)
    DeleteRequest = models.IntegerField(default=0,null=False, blank=False)
    EditRequest = models.IntegerField(default=0,null=False, blank=False)
    approved = models.IntegerField(default=0,null=False,blank=False)

orders/views/items.py
"""The class for logging to server"""
import logging

from django.utils.datastructures import MultiValueDictKeyError
from django.http import JsonResponse
from django.views import generic
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from orders.models import (
    ItemPrices, Supplier, Item)


logger = logging.getLogger(__name__)

@method_decorator(login_required, name='dispatch')
class ViewItems(generic.ListView):
    """View a list of saved catalog items."""
    model = Item
    template_name = 'accounting/items-catalog.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['itemprices_list'] = ItemPrices.objects.all()
        return context

def add_items(request):
    """Items are added to database"""
    try:
        name = request.POST['item_name']
        description = request.POST['item_description']

        item_obj = Item.objects.create(
            name=name,
            description=description
        )

        data = {
            'success_status': 1,
            'id': item_obj.id,
            'name': item_obj.name,
            'description': item_obj.description
        }
        return JsonResponse(data)
    except Exception as e:
        logger.exception(e)
        data = {
            'success_status': 0,
            'error_message': 'Unable to process request',
        }
        return JsonResponse(data)


def add_prices(request, pk):
    """Item prices are added to database"""
    success_status = 0  # initially success status is set to zero
    data = {}
    try:
        price = request.POST['price']
        supplier_id = request.POST['supplier']

        item_object = Item.objects.get(pk=pk)
        supplier_object = Supplier.objects.get(pk=supplier_id)

        item_price = ItemPrices.objects.create(
            supplier=supplier_object,
            item=item_object,
            price=price
        )

        data = {
            'id': item_price.id,
            'price': item_price.price,
            'supplier_id': item_price.supplier.id
        }
        success_status = 1
    except MultiValueDictKeyError as mk:
        logger.exception(mk)
        data = {
            'error_message': 'Unable to process request',
        }
    finally:
        data['success_status'] = success_status
        return JsonResponse(data)

@method_decorator(login_required, name='dispatch')
class CreateItemPrices(generic.DetailView):
    """View item prices page"""
    model = Item
    template_name = 'accounting/item-prices.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['supplier_list'] = Supplier.objects.all()
        return context


def delete_prices(request, pk):
    """Delete an existing price of a certain supplier"""
    success_status = 0
    try:
        item_price_id = request.GET.get('item_price_id', None)
        ItemPrices.objects.get(pk=item_price_id).delete()
        success_status = 1
        data = {
            'success_message': 'price deleted successfully'
        }
    except:
        data = {
            'error_message': 'Unable to process request'
        }
    finally:
        data['success_status'] = success_status
        return JsonResponse(data)

orders/views/login.py
"""The class for logging to server"""
import logging

from django.shortcuts import render 
from django.http import JsonResponse
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from orders.models import Item

logger = logging.getLogger(__name__)



def index(request):
    """Index page of the application."""
    return render(request, 'orders/login.html')


def login_web(request):
    """Authenticating a login request."""
    username = request.POST.get('username', None)
    password = request.POST.get('password', None)
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        user_group = user.groups.all()[:1].get().name
        # user.groups.all()[:1].get().name #can use this get the group of user

        if(user_group == "Manager" or user_group == "Supervisor"):
            return redirect('rulelist')
        elif(user_group == "Accounting Staff"):
            context = {'item_list': Item.objects.all() }
            return render(request, 'accounting/items-catalog.html', context)
        else:
            return render(request, 'orders/login.html')

    else:
        logger.error("User is not found: " + username + "  = " + password)
        context = {
            'login_error': 'username or password is incorrect.'
        }
        return render(request, 'orders/login.html', context)


def logout_view(request):
    """Logging out a logged in user."""
    logout(request)
    return render(request, 'orders/login.html')

orders/views/requests.py
"""The class for logging to server"""
import logging

from django.shortcuts import render 
from django.views import generic

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from orders.models import ( RequestOrders, Site, Orders, ItemPrices ) 


logger = logging.getLogger(__name__)

@method_decorator(login_required, name='dispatch')
class ViewRequests(generic.ListView):
    """"View a list of order requests generated by the site manager."""
    model = RequestOrders
    template_name = 'accounting/requests.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sites_list'] = Site.objects.all()
        return context

@method_decorator(login_required, name='dispatch')
class ViewPurchaseOrders(generic.ListView):
    """"View a list of purchase orders created by account staff"""
    model = Orders
    template_name = 'accounting/purchase-orders.html'


def view_order_request(request, pk):
    requestorders = RequestOrders.objects.get(pk=pk)
    price_list = ItemPrices.objects.filter(item=requestorders.item)
    context = {
        'price_list': price_list,
        'requestorders': requestorders
    }
    return render(request, 'accounting/purchase-order-create.html', context)

orders/templates/accounting/item-prices.html
{% extends '../accounts-base.html' %}
{% block title %}Items Prices{% endblock title %}

{% block stylesheet %}

{% endblock stylesheet %}

{% block content %}
<div id="page-wrapper">
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h1>Items Prices</h1>
            </div>
        </div>
        <div class="container-fluid">
            <div class="container-fluid">
                <p>Item : {{ item.name }} </p>
                {% if item.description %}
                <p><strong>Description : </strong></p>
                <pre>            {{ item.description }} </pre>
                {% endif %}
            </div>
            <div class="container-fluid">
                <div class="container-fluid">
                    <table class="table table-light" id="prices_table">
                        <thead class="thead-light">
                            <tr scope="row">
                                <th>#</th>
                                <th>Supplier</th>
                                <th>Price</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <form class="form form-inline">
                                    {% csrf_token %}
                                    <td> </td>
                                    <input id="itemId" class="form-control" type="text" name="item_id"
                                        style="display: none;" />
                                    <td>

                                        <div class="form-group col-4 m-2">
                                            <select id="supplierId" class="form-control selectpicker"
                                                data-live-search="true" name="supplier">
                                                <option value="default" disabled selected> -- Supplier</option>
                                                {% for supplier in supplier_list %}
                                                <option value="{{ supplier.id }}">{{ supplier.company_name }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </td>
                                    <td>

                                        <div class="form-group col-4  m-2">
                                            <input id="priceId" class="form-control" type="number" name="price" min="1">
                                        </div>
                                    </td>

                                    <td>
                                        <div class="form-group col-1">
                                            <input id="submit_btn" class="form-control btn btn-info" type="submit"
                                                value="Add">
                                        </div>

                                    </td>

                                </form>
                            </tr>
                            {% for price in item.itemprices_set.all %}
                            <tr id="{{ price.id }}">
                                <td scope="col"> {{ forloop.counter }} </td>
                                <td> {{ price.supplier.company_name }} </td>
                                <td class="text-right"> {{ price.price }}.00 </td>
                                <td class="text-right form-group col-1  m-2">
                                    <input id="remove_btn" class="btn btn-danger" type="submit" value="Remove">
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}
{% block javascript %}
<script>
    $(function () {

        $('#submit_btn').click(function () {

            var csrftoken = $("[name=csrfmiddlewaretoken]").val();
            supplier = $('#supplierId').val()
            price = $('#priceId').val()


            call_url = "{% url 'item_prices_add' item.id  %}"

            $.ajax({
                url: call_url,
                type: 'POST',
                headers: {
                    "X-CSRFToken": csrftoken
                },
                data: {
                    'price': price,
                    'supplier': supplier,
                },
                dataType: 'json',
                success: function (data) {
                    if (data.success_status == 1) {

                    } else {
                        alert(data.error_message);
                    }
                }
            });
        });

        $('#remove_btn').click(function () {
            item_price_id = $(this).parent().parent().attr('id')
            
            $.ajax({
                url: "{% url 'item_prices_remove' item.id %}",
                dataType: 'json',
                data: {
                    'item_price_id': item_price_id
                },
                success: function (data) {
                    if (data.success_status == 1) {
                        alert(data.success_message)
                        $('#'+item_price_id).remove();
                        
                    } else {
                        alert(data.error_message);
                    }
                }
            });
        });


    });
</script>
{% endblock javascript %}

orders/templates/accounting/purchase-order-create.html
{% extends '../accounts-base.html' %}
{% block title %}Items Prices{% endblock title %}

{% block stylesheet %}

{% endblock stylesheet %}

{% block content %}
<div id="page-wrapper">
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h2>Purchase Order: </h2>
            </div>
        </div>
        <div class="container-fluid">
            <div>
                <div class="row">
                    <div class="col-md-4">
                        <h5>Request Id : #{{ requestorders.id }}</h5>
                    </div>
                    <div class="col-md-4">
                        <h5>Requestee : {{ requestorders.site.employee_set.all.0 }}</h5>
                    </div>
                    <div class="col-md-4">
                        <h5>Site : {{ requestorders.site.name }}</h5>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <h5>Item : {{ requestorders.item.name }}</h5>
                    </div>
                    <div class="col-md-4">
                        <h5>Quantity : {{ requestorders.quantity }}</h5>
                    </div>
                    <div class="col-md-4">
                        <h5>Expected Date: {{ requestorders.expected_date }}</h5>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <h5>Comments: </h5>
                        <pre>           <p>{{ requestorders.comment }}</p>       </pre>
                    </div>
                </div>


            </div>

            <div>
                {% if price_list %}
                <table class="table table-light">
                    <thead class="thead-light">
                        <tr>
                            <th>#</th>
                            <th>Supplier</th>
                            <th>Price</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                        <form id="orders_form " method="POST">
                            {% csrf_token %}
                            {% for price in price_list %}
                            <tr>
                                <td> {{ forloop.counter }} </td>
                                <td> {{ price.supplier.company_name }} </td>
                                <td> {{ price.price }} </td>
                                <td><input id="supplier-id" class="form-check-input" type="radio" name="item_price_id"
                                        value="{{ price.id }}">
                                </td>
                            </tr>
                            {% endfor %}
                            <button style="float: right; margin-left: 2;" class="btn btn-info" type="submit">Create
                                Purchase Order</button>
                            <button class="btn btn-success" type="submit">Save as a draft</button>
                        </form>
                    </tbody>
                </table>


                {% else %}
                <h4>No Prices added for item to display</h4>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block javascript %}
<script>
    $(function () {

        $('.btn').click(function () {
            
            var csrftoken = $("[name=csrfmiddlewaretoken]").val();
            var item_price_id = $('input[type="radio"][name="item_price_id"]:checked').val()
            var order_id = '{{ requestorders.orders.id }}'
            var request_id = '{{ requestorders.id }}'

            var create_url = "{% url 'purchase_order_add' requestorders.id  %}"
            var update_url =  "{% url 'update_purchase_order' request_id=requestorders.id order_id=999 %}"
            update_url = update_url.replace('999', order_id)
            call_url = order_id ? update_url: create_url
            
            $.ajax({
                url: call_url,
                type: 'POST',
                headers: {
                    "X-CSRFToken": csrftoken
                },
                data: {
                    'item_price_id': item_price_id,
                },
                dataType: 'json',
                success: function (data) {
                    if (data.success_stat == 1) {
                        if(typeof item_price_id != undefined){
                            window.location.href = '{%url "list_purchase_order" %}'
                        }else{
                            window.location.href = '{%url "list_order_requests" %}'
                        }
                    } else {
                        alert(data.error_message);
                    }
                }
            });

        });


    });
</script>
{% endblock javascript %}

orders/templates/accounting/purchase-orders.html
{% extends '../accounts-base.html' %}
{% block title %}Items Prices{% endblock title %}

{% block stylesheet %}

{% endblock stylesheet %}

{% block content %}
<div id="page-wrapper">
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h2>Purchase Orders</h2>
            </div>
        </div>
        <div class="container-fluid">
            <div class="card shadow bg-white">
                <div class="card-body">
                    <table class="table table-light">
                        <thead class="thead-light">
                            <tr>
                                <th>order id</th>
                                <th>site </th>
                                <th>order status</th>
                                <th>active </th>
                                <th>expected date</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in orders_list %}
                            <tr>
                                <td> #{{ order.id }} </td>
                                <td> {{ order.site.name }} </td>
                                <td> {{ order.status.status }} </td>
                                <td style="color: #214761;"> {{ order.active }} </td>
                                <td> {{ order.delivery_date }} </td>
                                <td><a href="{% url 'view_order_request' order.request.id %}"><button class="btn btn-warning" type="button">Open</button></a>  </td>
                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>


                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}
{% block javascript %}
<script>

</script>
{% endblock javascript %}

orders/templates/accounting/requests.html
{% extends '../accounts-base.html' %}
{% block title %}Order Requests{% endblock title %}

{% block stylesheet %}

{% endblock stylesheet %}

{% block content %}
<div id="page-wrapper">
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h2>Order Requests</h2>
            </div>
            <br>
            <br>
            {% for site in sites_list %}
            <div class="container-fluid bg-light">
                <h4 class="text-info">{{ site.name }} </h4>
                <table class="table table-light bg-info">
                    {% for requestorder in requestorders_list  %}
                    {% if requestorder.site == site%}
                    <tbody>
                        <tr>
                            <td>#{{ requestorder.id }}</td>
                            <td class="text-right">{{ requestorder.item.name }} </td>
                            <td class="text-right">{{ requestorder.quantity }}</td>
                            <td class="text-right">{{ requestorder.quantity_type }}</td>
                            <td class="text-right">{{ requestorder.status.status }}</td>
                            <td class="text-right">{{ requestorder.expected_date }}</td>
                            <td class="text-right"><a href="{% url 'view_order_request' requestorder.id %}">
                                    <button class="btn btn-warning" type="button">Open</button>
                                </a>
                            </td>
                        </tr>
                    </tbody>
                    {% endif %}
                    {% endfor %}
                </table>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}
{% block javascript %}
<script>
    $(function () {

    });

</script>
{% endblock javascript %}